# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rmessage.proto\"\x99\x01\n\x0b\x43hatMessage\x12\x0f\n\x07\x66rom_id\x18\x01 \x01(\x05\x12\r\n\x05to_id\x18\x02 \x01(\x05\x12\r\n\x05lc_id\x18\x03 \x01(\x05\x12\'\n\nheart_beat\x18\x04 \x01(\x0b\x32\x11.HeartBeatMessageH\x00\x12$\n\x0ctext_message\x18\x05 \x01(\x0b\x32\x0c.TextMessageH\x00\x42\x0c\n\ntest_oneof\"\x1e\n\x0bTextMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x12\n\x10HeartBeatMessageb\x06proto3')
)




_CHATMESSAGE = _descriptor.Descriptor(
  name='ChatMessage',
  full_name='ChatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='from_id', full_name='ChatMessage.from_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='to_id', full_name='ChatMessage.to_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lc_id', full_name='ChatMessage.lc_id', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='heart_beat', full_name='ChatMessage.heart_beat', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text_message', full_name='ChatMessage.text_message', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='test_oneof', full_name='ChatMessage.test_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=18,
  serialized_end=171,
)


_TEXTMESSAGE = _descriptor.Descriptor(
  name='TextMessage',
  full_name='TextMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='TextMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=203,
)


_HEARTBEATMESSAGE = _descriptor.Descriptor(
  name='HeartBeatMessage',
  full_name='HeartBeatMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=223,
)

_CHATMESSAGE.fields_by_name['heart_beat'].message_type = _HEARTBEATMESSAGE
_CHATMESSAGE.fields_by_name['text_message'].message_type = _TEXTMESSAGE
_CHATMESSAGE.oneofs_by_name['test_oneof'].fields.append(
  _CHATMESSAGE.fields_by_name['heart_beat'])
_CHATMESSAGE.fields_by_name['heart_beat'].containing_oneof = _CHATMESSAGE.oneofs_by_name['test_oneof']
_CHATMESSAGE.oneofs_by_name['test_oneof'].fields.append(
  _CHATMESSAGE.fields_by_name['text_message'])
_CHATMESSAGE.fields_by_name['text_message'].containing_oneof = _CHATMESSAGE.oneofs_by_name['test_oneof']
DESCRIPTOR.message_types_by_name['ChatMessage'] = _CHATMESSAGE
DESCRIPTOR.message_types_by_name['TextMessage'] = _TEXTMESSAGE
DESCRIPTOR.message_types_by_name['HeartBeatMessage'] = _HEARTBEATMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChatMessage = _reflection.GeneratedProtocolMessageType('ChatMessage', (_message.Message,), dict(
  DESCRIPTOR = _CHATMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:ChatMessage)
  ))
_sym_db.RegisterMessage(ChatMessage)

TextMessage = _reflection.GeneratedProtocolMessageType('TextMessage', (_message.Message,), dict(
  DESCRIPTOR = _TEXTMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:TextMessage)
  ))
_sym_db.RegisterMessage(TextMessage)

HeartBeatMessage = _reflection.GeneratedProtocolMessageType('HeartBeatMessage', (_message.Message,), dict(
  DESCRIPTOR = _HEARTBEATMESSAGE,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:HeartBeatMessage)
  ))
_sym_db.RegisterMessage(HeartBeatMessage)


# @@protoc_insertion_point(module_scope)
